version: '2'
services:
    jhmapa360services-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        command: mongos --configdb jhmapa360services-mongodb-config
    jhmapa360services-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    jhmapa360services-mongodb-config:
        image: mongo:3.4.10
        container_name: jhmapa360services-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
