version: '2'
services:
    jhmapa360services-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhMapa360Services/mongodb/:/data/db/
